import './globals.css'
import { Roboto } from 'next/font/google';

import ResponsiveAppBar from './AppBar';

const roboto = Roboto({ subsets: ['latin'], weight: "100" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  )
}
