import './globals.css'
import { Roboto } from 'next/font/google';

const roboto = Roboto({ subsets: ['latin'], weight: "100" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <h1>this should appear to be an header</h1>
        {children}
      </body>
    </html>
  )
}
